server:
  port: 0

spring:
  application:
    name: micro-commerce-web-notification

  kafka:
    bootstrap-servers: kafka-1:9092
    producer:
      bootstrap-servers: kafka-1:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    retry:
      topic:
        enabled: true

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}

  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka
    register-with-eureka: true
    fetch-registry: true
